config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :users
  resources :microposts
  
  get '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new', via: :all
  get '/signout', to: 'sessions#destroy'
  
  get '/chat', to: 'static_pages#chat'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  root 'static_pages#home'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
  
  order('external_updated_at')
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :microposts, dependent: :destroy
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A\w+.\w+@\w+\.(com|org|net|\w+\.(com|org|net))\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 6}
  validates :password_confirmation, presence: true
  
  def feed
    Micropost.where("user_id = ?", id)
  end
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user
  
  def create
    @micropost = current_user.microposts.build(params.require(:micropost).permit(:content))
    if @micropost.save
      flash[:success] = "Micropost created."
      redirect_to chat_path
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end
  
  def destroy
    
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
    flash.now[:error] = "Invalid email/password combination"
    render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end
  
  def chat
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
    
  end
  
  def about
    
  end
  
  def contact
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
   
  def new
    @user = User.new
  end
  
   def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Account created."
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      sign_in @user
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_path
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end
  
    def admin_user
      redirect_to root_path unless current_user.admin?
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  
  def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "You must sign in to view this page."
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = {size:50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		A Feliks Montez System
	</small>
	<nav>
		<ul>
			<li><%= link_to "Help ",   help_path %></li>
			<li><%= link_to "About",   about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "itbase", root_path, id: "logo", class: "nabvar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!--<form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home ", root_path %></li>
				<% if signed_in? %>
				  <li><%= link_to "Chat ", chat_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "destroy" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_user.html.erb
<% @users.each do |user| %>
	<li>
		<%= gravatar_for user, size: 52 %>
		<%= link_to user.name, user %>
		<% if current_user.admin? && !current_user?(user) %>
			| <%= link_to "delete", user, method: :delete, confirm: "Are you sure?" %>
		<% end %>
	</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ITbase</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  	<div class="center hero-unit">
	  	<% flash.each do |key, value| %>
	  		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
	  	<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params)  if Rails.env.development? %>
	</div>
  </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<% @microposts.each do |micropost| %>
	<li>
		<span class="content"><%= micropost.content %></span>
		<span class="timestamp">
			Posted <%= time_ago_in_words(micropost.created_at) %> ago.
		</span>
	</li>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<% link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: @micropost %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 52 %>
</a>
<h2 class="left lower2"><%= current_user.name %></h2>
<span class="lower1"><%= link_to "view my profile", current_user %></span>
<span class=""><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>This is the About Us page.</p>

app/views/static_pages/chat.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="left">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section class="span4">
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="span6 right">
			<h2 class="center">Micropost Feed</h2>
			<%= render 'shared/feed' %> 
		</div>
	</div>
<% else %>
<% end %>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>
<p>This is the Contact Us page.</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>This is the help page.</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to ITbase!</h1>
	<p>This is the home page.</p>
	
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: @user %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
			
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>
		
		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails" target="_blank">change</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
		<%= render 'layouts/user' %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: @user%>
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
			
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Create my Account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="span4">
		<section>
			<h2>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h2>
		</section>
	</aside>
	<div class="span8">
		<% if @user.microposts.any? %>
		<h3>Microposts (<%= @user.microposts.count %>)</h3>
		<% end %>
		
		<%= will_paginate @microposts %>
		
		<ol class="microposts">
			<%= render @microposts %>
		</ol>
		
		<%= will_paginate @microposts %>
		
	</div>
</div>